vsim -do collectCoverage4s.do
vsim -do collectCoverage8s.do
vsim -do collectCoverage12s.do
vsim -do collectCoverage16s.do
vsim -do collectCoverage20s.do
vsim -do collectCoverage24s.do
vsim -do collectCoverage28s.do
vsim -do collectCoverage32s.do
vsim -do collectCoverage36s.do
vsim -do collectCoverage40s.do
vsim -do collectCoverage44s.do
vsim -do collectCoverage48s.do
vsim -do collectCoverage52s.do
vsim -do collectCoverage56s.do
vsim -do collectCoverage60s.do
vsim -do collectCoverage64s.do
vsim -do collectCoverage68s.do
vsim -do collectCoverage72s.do
vsim -do collectCoverage76s.do
vsim -do collectCoverage80s.do
vsim -do collectCoverage84s.do
vsim -do collectCoverage88s.do
vsim -do collectCoverage92s.do
vsim -do collectCoverage96s.do
vsim -do collectCoverage100s.do
vsim -do collectCoverage104s.do
vsim -do collectCoverage108s.do
vsim -do collectCoverage112s.do
vsim -do collectCoverage116s.do
vsim -do collectCoverage120s.do
vsim -do collectCoverage124s.do
vsim -do collectCoverage128s.do
vsim -do collectCoverage132s.do
vsim -do collectCoverage136s.do
vsim -do collectCoverage140s.do
vsim -do collectCoverage144s.do
vsim -do collectCoverage148s.do
vsim -do collectCoverage152s.do
