vsim  -do  collectCoverage10s.do
vsim  -do  collectCoverage30s.do
vsim  -do  collectCoverage50s.do
vsim  -do  collectCoverage70s.do
vsim  -do  collectCoverage90s.do
vsim  -do  collectCoverage110s.do
vsim  -do  collectCoverage130s.do
vsim  -do  collectCoverage150s.do
vsim  -do  collectCoverage170s.do
vsim  -do  collectCoverage190s.do
vsim  -do  collectCoverage210s.do
vsim  -do  collectCoverage230s.do
vsim  -do  collectCoverage250s.do
vsim  -do  collectCoverage270s.do
vsim  -do  collectCoverage290s.do
vsim  -do  collectCoverage310s.do
vsim  -do  collectCoverage330s.do
vsim  -do  collectCoverage350s.do
vsim  -do  collectCoverage370s.do
vsim  -do  collectCoverage390s.do
vsim  -do  collectCoverage410s.do
vsim  -do  collectCoverage430s.do
vsim  -do  collectCoverage450s.do
vsim  -do  collectCoverage470s.do
vsim  -do  collectCoverage490s.do
vsim  -do  collectCoverage510s.do
vsim  -do  collectCoverage530s.do
