vsim -do collectCoverage5s.do
vsim -do collectCoverage15s.do
vsim -do collectCoverage25s.do
vsim -do collectCoverage35s.do
vsim -do collectCoverage45s.do
vsim -do collectCoverage55s.do
vsim -do collectCoverage65s.do
vsim -do collectCoverage75s.do
vsim -do collectCoverage85s.do
vsim -do collectCoverage95s.do
vsim -do collectCoverage105s.do
vsim -do collectCoverage115s.do
vsim -do collectCoverage125s.do
vsim -do collectCoverage135s.do
vsim -do collectCoverage145s.do
vsim -do collectCoverage155s.do
vsim -do collectCoverage165s.do
vsim -do collectCoverage175s.do
vsim -do collectCoverage185s.do
vsim -do collectCoverage195s.do
vsim -do collectCoverage205s.do
vsim -do collectCoverage215s.do
vsim -do collectCoverage225s.do
vsim -do collectCoverage235s.do
vsim -do collectCoverage245s.do
vsim -do collectCoverage255s.do
