vsim -do collectCoverage1s.do
vsim -do collectCoverage3s.do
vsim -do collectCoverage5s.do
vsim -do collectCoverage7s.do
vsim -do collectCoverage9s.do
vsim -do collectCoverage11s.do
vsim -do collectCoverage13s.do
vsim -do collectCoverage15s.do
vsim -do collectCoverage17s.do
vsim -do collectCoverage19s.do
vsim -do collectCoverage21s.do
vsim -do collectCoverage23s.do
vsim -do collectCoverage25s.do
vsim -do collectCoverage27s.do
vsim -do collectCoverage29s.do
vsim -do collectCoverage31s.do
vsim -do collectCoverage33s.do
vsim -do collectCoverage35s.do
vsim -do collectCoverage37s.do
vsim -do collectCoverage39s.do
vsim -do collectCoverage41s.do
vsim -do collectCoverage43s.do
vsim -do collectCoverage45s.do
vsim -do collectCoverage47s.do
vsim -do collectCoverage49s.do
vsim -do collectCoverage51s.do
vsim -do collectCoverage53s.do